debug.storePassword=android
debug.keyAlias=androiddebugkey
debug.keyPassword=android
release.storePassword=android
release.keyAlias=androiddebugkey
release.keyPassword=android
releaseUpload.storePassword=android
releaseUpload.keyAlias=androiddebugkey
releaseUpload.keyPassword=android
